# Generated by Django 3.2.4 on 2021-06-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('contact_number', models.CharField(max_length=12)),
                ('contact_name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.IntegerField(default='43701')),
                ('weight', models.IntegerField()),
                ('pracel_type', models.CharField(max_length=500)),
            ],
        ),
    ]
