# Generated by Django 3.2.4 on 2021-06-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antilopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=12)),
                ('contact_number', models.IntegerField()),
                ('address', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField()),
            ],
        ),
    ]
